version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/"
    schedule:
      day: friday
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "build(deps)"
    reviewers:
      - ioV9x
    groups:
      better-sqlite3:
        patterns:
          - "@types/better-sqlite3"
          - "better-sqlite3"
      bunyan:
        patterns:
          - "@types/bunyan"
          - "bunyan"
      electron:
        patterns:
          - "@electron/*"
          - "electron"
      electron-forge:
        patterns:
          - "@electron-forge/*"
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
      ibm-carbon:
        patterns:
          - "@carbon/*"
          - "@ibm/*"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
      vite:
        patterns:
          - "vite"
          - "vite-tsconfig-paths"
          - "vitest" # typing interdependencies
    ignore:
      # depends on the nodejs version bundled with electron
      - dependency-name: "@types/node"
        update-types: [version-update:semver-minor, version-update:semver-major]
      # electron ugrades usually require a bit of manual work and should always
      # be smoke tested. Also it is good idea to wait for the first patch…
      - dependency-name: "electron"
        update-types: [version-update:semver-major]
      # next sass update generates warnings in combination with carbon
      # wait for carbon to fix the warnings
      - dependency-name: "sass"
